package ru.agalkingps.mealapp.order_flow.ui.theme

import androidx.compose.ui.graphics.Color

val mealLightPrimary = Color(0xFF825500)
val mealLightOnPrimary = Color(0xFFFFFFFF)
val mealLightPrimaryContainer = Color(0xFFFFDDAE)
val mealLightOnPrimaryContainer = Color(0xFF2A1800)
val mealLightSecondary = Color(0xFF6F5B40)
val mealLightOnSecondary = Color(0xFFFFFFFF)
val mealLightSecondaryContainer = Color(0xFFFADEBC)
val mealLightOnSecondaryContainer = Color(0xFF271904)
val mealLightTertiary = Color(0xFF516440)
val mealLightOnTertiary = Color(0xFFFFFFFF)
val mealLightTertiaryContainer = Color(0xFFD3EABC)
val mealLightOnTertiaryContainer = Color(0xFF102004)
val mealLightError = Color(0xFFBA1B1B)
val mealLightErrorContainer = Color(0xFFFFDAD4)
val mealLightOnError = Color(0xFFFFFFFF)
val mealLightOnErrorContainer = Color(0xFF410001)
val mealLightBackground = Color(0xFFFCFCFC)
val mealLightOnBackground = Color(0xFF1F1B16)
val mealLightSurface = Color(0xFFFCFCFC)
val mealLightOnSurface = Color(0xFF1F1B16)
val mealLightSurfaceVariant = Color(0xFFF0E0CF)
val mealLightOnSurfaceVariant = Color(0xFF4F4539)
val mealLightOutline = Color(0xFF817567)
val mealLightInverseOnSurface = Color(0xFFF9EFE6)
val mealLightInverseSurface = Color(0xFF34302A)
val mealLightPrimaryInverse = Color(0xFFFFB945)

val mealDarkPrimary = Color(0xFFFFB945)
val mealDarkOnPrimary = Color(0xFF452B00)
val mealDarkPrimaryContainer = Color(0xFF624000)
val mealDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val mealDarkSecondary = Color(0xFFDDC3A2)
val mealDarkOnSecondary = Color(0xFF3E2E16)
val mealDarkSecondaryContainer = Color(0xFF56442B)
val mealDarkOnSecondaryContainer = Color(0xFFFADEBC)
val mealDarkTertiary = Color(0xFFB8CEA2)
val mealDarkOnTertiary = Color(0xFF243516)
val mealDarkTertiaryContainer = Color(0xFF3A4C2B)
val mealDarkOnTertiaryContainer = Color(0xFFD3EABC)
val mealDarkError = Color(0xFFFFB4A9)
val mealDarkErrorContainer = Color(0xFF930006)
val mealDarkOnError = Color(0xFF680003)
val mealDarkOnErrorContainer = Color(0xFFFFDAD4)
val mealDarkBackground = Color(0xFF1F1B16)
val mealDarkOnBackground = Color(0xFFEAE1D9)
val mealDarkSurface = Color(0xFF1F1B16)
val mealDarkOnSurface = Color(0xFFEAE1D9)
val mealDarkSurfaceVariant = Color(0xFF4F4539)
val mealDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val mealDarkOutline = Color(0xFF9C8F80)
val mealDarkInverseOnSurface = Color(0xFF32281A)
val mealDarkInverseSurface = Color(0xFFEAE1D9)
val mealDarkPrimaryInverse = Color(0xFF624000)
